### ISSUE TITLE
Giving you feedback on Lazarus --os=win32 --cpu=i386 for test_cwRuntime

### ISSUE THREAD

**Issue by gcarreno** [chapmanworld/cwRuntime#2]
Hi Craig,

I'm attaching the binary and the xml file with the result of running test_cwRuntime on Lazarus with `--os=win32` `--cpu=i386`

TLDR: Builds/Fails tests

Result file: [test_cwRuntime-i386-win32.txt](https://github.com/chapmanworld/cwRuntime/files/4501850/test_cwRuntime-i386-win32.txt)

Binary: [test_cwRuntime.zip](https://github.com/chapmanworld/cwRuntime/files/4501872/test_cwRuntime.zip)

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Craig,

Per commit 7d9a264, it is now Building AND Passing tests.

Result file: [test_cwRuntime-win32-i386.xml.txt](https://github.com/chapmanworld/cwRuntime/files/4513599/test_cwRuntime-win32-i386.xml.txt)

Binary: [test_cwRuntime-win32-i386.zip](https://github.com/chapmanworld/cwRuntime/files/4513602/test_cwRuntime-win32-i386.zip)


Cheers,
Gus

**Comment by chapmanworld** [comment]
This should now build and pass tests.

**Comment by gcarreno** [comment]
Hey Craig,

Can confirm, will close.

Cheers,
Gus
