### ISSUE TITLE
Giving you feedback on Lazarus --os=linux --cpu=x86_64 for test_cwRuntime

### ISSUE THREAD

**Issue by gcarreno** [chapmanworld/cwRuntime#3]
Hi Craig,

I'm attaching the binary and the xml file with the result of running test_cwRuntime on Lazarus with `--os=linux` `--cpu=x86_64`

TLDR: Builds/Fails tests

Result file: [test_cwRuntime-x86_64-linux.txt](https://github.com/chapmanworld/cwRuntime/files/4501910/test_cwRuntime-x86_64-linux.txt)

Binary: [test_cwRuntime-x86_64-linux.zip](https://github.com/chapmanworld/cwRuntime/files/4501911/test_cwRuntime-x86_64-linux.zip)

Cheers,
Gus

**Comment by chapmanworld** [comment]
This should now build and pass tests.

**Comment by gcarreno** [comment]
Hey Craig,

Can confirm, will close.

Cheers,
Gus
