### ISSUE TITLE
General CI discussion.

### ISSUE THREAD

**Issue by chapmanworld** [chapmanworld/cwRuntime#7]
Continue discussion from [https://github.com/chapmanworld/cwRuntime/issues/4](https://github.com/chapmanworld/cwRuntime/issues/4 
)
Please don't worry at all about sounding condescending or anything like that. I'm an elder digital native and therefore tend not to read content emotionally on the internet, it's just good 'Netiquette' :-)  I actually appreciate alternative or confirming suggestions.

There is a windows version of rsync but I honestly didn't even consider using it. The advantage that SSH has is that the same protocol allows for both transfer of files, and execution of instructions on the target without having to build any 'paserver' like tool for the target. SSH should be available on all intended targets, so it just made sense.  The only real snag is that using plink to run the unit test doesn't return a process error level/code if the tests fail.  Since I wrote the unit test framework in use, I should be able to provide a customization of the report to solve this problem, or else simply parse the XML with a little utility.

Regarding containerization, I'm also not a huge fan of this technology. I understand it can have some advantages regarding CPU utilization and such, however, I find working with containers to be a little more challenging than local VMs.

The virtual machine that I have configured will be running inside QEMU on Windows, which multiplexes CPU cores (essentially the same CPU benefits as a container) while giving me a full graphical desktop when I need it to configure.  i.e. I installed lazarus using fpcupdeluxe on this VM using Xfce desktop, then simply ran the VM again in headless mode - now I can lazbuild on it.

**Comment by gcarreno** [comment]
Hey Craig,

>  ... I actually appreciate alternative or confirming suggestions.

Thanks for the vote of confidence!! Really appreciated!!

> ... without having to build any 'paserver' like tool for the target

Yeap, gotcha. I'll have to agree with your reasoning!

> Regarding containerization, I'm also not a huge fan of this technology.

Well, to be honest, containerization would only be useful for Linux targets. Win, Android, macOS and iOS would still have to be done the way you're doing it.

Unless you can find good (as in free) images for those platforms, that can be run on either a Windows or Linux host machine. If so, then, in my opinion, it would make sense to use it.

> The virtual machine that I have configured will  [.....] ran the VM again in headless mode - now I can lazbuild on it.

This does seem quite nifty and well thought out!! Hope you can get it all to mesh nicely!

Cheers,
Gus
